sequencing: "pe"

input_dir: "/home/jverwilt/totalRNApipeline/data"
output_dir: "/home/jverwilt/totalRNApipeline/out"

reference:
  fasta: /home/jverwilt/resources/genome/chm13/chm13_MT_spikes.fa
  gtf: /home/jverwilt/resources/gtf/chm13/chm13_MT_spikes.gtf
  bed: /home/jverwilt/resources/gtf/chm13/chm13_MT_spikes.bed

index:
  star: /home/jverwilt/resources/indexes/chm13/STAR_index