
version: "v3"
sequencing: "pe"
deconvolution: "no"

input_dir: "/home/jverwilt/totalRNApipeline/tests/input/v3_pe"
output_dir: "/home/jverwilt/totalRNApipeline/tests/output/v3_pe"

reference:
  fasta: /home/jverwilt/resources/genome/chm13/chm13_MT_spikes.fa
  gtf: /home/jverwilt/resources/gtf/chm13/chm13_MT_spikes.gtf
  bed: /home/jverwilt/resources/gtf/chm13/chm13_MT_spikes.bed

index:
  star: /home/jverwilt/resources/indexes/chm13/STAR_index

other:
  prepare_deconv: /home/jverwilt/totalRNApipeline/resources/chm13_MT_prepare_deconv.tsv
